/*Use Exercise database for answer these question from previous files*/

--1st question
/* 
Write a SQL query to select all the salespeople. Return salesman_id, name, city, 
commission with the percent sign (%).*/select salesman_id,name,city, convert(varchar(4),comission*100)+'%' as comission from salesman

--2nd question
/*
Write a SQL query to find the number of orders booked for each day.
*/
select count(order_date) as number_of_orders, order_date from orders group by order_date

--3rd question
/*
Write a SQL query to show all the orders. Sort the result-set in ascending order 
by ord_no. Return all fields.*/
select * from orders order by order_no 

--4th question
/*
Write a SQL query to show all the customers. Sort the result-set by customer_id. 
Return cust_name, city, grade.
*/
select customer_name, city, grade from customer order by customer_id

--5th question
/*
Identify the maximum purchase amount generated by each salesperson for each 
order date by writing a SQL query. Sort the result set in ascending order by 
salesperson ID and order date.
*/
select salesman_id,order_date, max(purch_amt) from orders group by salesman_id, order_date
order by salesman_id,order_date

--6th question
/*
Create a SQL query that records the number of distinct orders and the maximum 
purchase amount for every client.
*/
select customer_id, count(distinct order_no),max(purch_amt) from orders group by customer_id
